language: ruby
rvm:
- 2.6.3

before_script:
- chmod +x ./script/cibuild

script: "./script/cibuild"

branches:
  only:
  - master

  env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

  addons:
  apt:
    packages:
    - libcurl4-openssl-dev
sudo: false

cache: bundler

notifications:
  email: false

before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
