language: ruby
rvm:
- 2.6.3
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: YwOWCyfw8rqliA+t0Dbrygg4vA/z22GBRe0NnISu9ZkIOva3FD6tl7hNePHuYP604edFUzZd7YPIuwdDemKZuBLAa5Yd9WdqSZLqvANSjFSWyVm9VKhPA3NoOVYK8TVodfeg64XCIkLzM8zta8foqwsgVtRO2SJGRZWVUcoIYMPqtyiSdBs0TutX7c/a3qgarAdF2rO/jDp7O8M3EFS2rZpadtuBg94ZKx30V3FJebaRfMtme4sruSdMAA/X7JVkFD5G/Jt+hBXw/JMcPUKQUDd/Nd9zBGl60yJmmLwCeYuSBokNqMz+YIoPMm41Ly2gWuTzQ2I4vQRCD84eZoFK4sjUFbVkNwoY/XlWbnKWRgoaRoMRmzP+y65FlLemS25w2kww/rAPfMbkre9Uj1yJOnltY16P2WW1y8Jjm9UnHamZzsyTEtyVPGMFqkvZNSPCAgMCECfVdUeVtG7Pa7ZyDcfG4F59F9UmHCVFbzOnCjGOTY+Ih0dOYpKjwcXmWUig4Sr0+G/XeRtqEKIpOqjZVu/Xvt6S2vv5qVisR8yEOtkzgwcR6MF9OhjSAEzfQVU8t4C3tBOi69fq1ax5mFEKMwiGRA/lDvfcRsa/Ctwnia6l+u86q40me+xFtkpuGK6cBraQlpgqj+Vj9SPgX+QqAAhtkadCDwdBW2mjRQ3vYGE=
  - secure: YKpShRfq7flNW1c746YEdjNBYfvqLGQ8kIxaOiDW12iXqq0l4OhQBYfL+V0DOVkCp9MzjykOMvpO2UiS/05NMo+FJj4bF2uT6+xD9TT6EHrwp2lNM866O1Ntd0CJnx8ozHldhy9wr2aT61rPJuYSP8Isx2Pjp//zllLl6hHyI56MPIsi+lBjkJh561MjgZJYHWAPu3hs3M4ntbjZANbNNLoGVPCVaYxYT2f47R0CcaSOBytOLV2BW4oj6kCDWb7FwH0J48epU0md+n3F9KOu+8ntKWrC5a+TqN88KSYLe7eugVBZc0g0oLtPIth9hdACiC4MZ0PT72MzD1xjUhi9fZhg6EBSDdo/olgjNG2fYUmfzO7QOvFNdTesZbsF647xXzaA+MShjCqkW1pHCKm+KxjFnpfvzP3+SotwmBDFmFV/V9iJMrx8AUGPYxEkz0/mYhY6/ANLCXf7tdiq6fauJetDyVEfAsrMTNqG6iV0GuxUOuxe3SN1ZD7UKyJRVwsdMBMLzH80WPyLE+6ZmrsgLHKPR1F8p0TCM7S2xkAh/Cqrc7UHYC4TkjoKtpcQ83DroFLolLWRXdn4AL+iicv4JzeeonVSmSMdpr3GGVpNyDluasyi8qdve9WYNlQjYmYvepztIKwKeXfPMyWICw6xNk+oAYHs+DnQl5OuW6KsLh4=
  - secure: tBGPA6pyWKc81S3G0nBgMBWITaDuywnxLmqD82IZ+0IsDvilR2TGt4i/Lox+UEie1+ztMUH4PpeiakLAQYjT+EtXcRMuKh9ur6VdBHUO0ZGe6ssNzAWjibBGLKGJuS6StoDD+/i9AuMASi/+xzmLs/Z/TKSlLdrUkw+gOC2+n7uL/LISr46IgwgZxAkX42mezlYSkAiO0EbL0qWLIwOka1IDNp18U6TpZyI/aao/nNs3zGGj4wgCNZP0MH2NVlPppPwudCIL5rCrAzhnuqyorOghDeo2z3m3NwvPGwqeWBKMRcMv7JqfAr7DsYrZTs1pzvvaUCNHWa2f7hM5Bq6ehR/u5EIeM3f4GytZsYxj2uzYa+rh+7aaEitgRrfEK0cAhUeymBaI0xey8ROleWx1X2C3QBzBA/CPij88FYnY/GOqxG32y3Ejj33wpzzIXab14a2QLxvchm+qXdITdPjoobrAfWrK19yjjcJQgTsx9A9fjNAerxaSVC+CZFnGOMinSzVNOBGu5nU0693+SBcj5SSDeS00hSS5wuCsGyecX8j8UbvdQf/2d3jEy4nhQpbG1jgSQyrrFdCiE/xmu81QImBm1mr4vN77X2wsBl2xPITaX5MGbIrQyueJNVU61e8aTCmQcC1SDrQ0QvKUTyAcT8NC5gosq8pfyGgs6sVWCVc=
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
sudo: false
cache: bundler
notifications:
  email: false
before_deploy:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- echo -e "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet --delete-after _site/* $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DIRECTORY
  on:
    branch: master
